version: '3'

services:

  customer:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "4000:8080"
    environment:
      - BILLING_SERVICE_URL=http://billing:8080
      - DELIVERY_SERVICE_URL=http://delivery:8080

  billing:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "4001:8080"

  delivery:
    build:
      context: ./delivery-service
    container_name: delivery-service
    ports:
      - "4002:8080"
    environment:
      - ADDRESS_VALIDATION_SERVICE_URL=http://address-validation:8080

  address-validation:
    build:
      context: ./address-validation-service
    container_name: address-validation-service
    ports:
      - "4003:8080"

  keycloak:
    image: jboss/keycloak:11.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
    ports:
      - "9191:8080"
    volumes:
      - ./keycloak/:/opt/jboss/keycloak/standalone/data/
